# Generated by Django 2.2.6 on 2019-10-24 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('requireLoggedIn', models.BooleanField(default=False)),
                ('maxTimeEvaluation', models.IntegerField(default=0)),
                ('starttime_evaluation', models.DateTimeField(blank=True, null=True)),
                ('endtime_evaluation', models.DateTimeField(blank=True, null=True)),
                ('limitNumberofEvaluation', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('private', 'Private'), ('public', 'Public'), ('close', 'Close')], default='open', max_length=10)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
